---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-failover-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-failover-operator
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["kopf.dev"]
    resources: ["clusterkopfpeerings"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["agones.dev"]
    resources: ["gameservers"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["failover.k8s.io"]
    resources: ["nodefailovers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["failover.k8s.io"]
    resources: ["nodefailovers/status"]
    verbs: ["get", "update", "patch"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-failover-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-failover-operator
subjects:
  - kind: ServiceAccount
    name: node-failover-operator
    namespace: default